### ISSUE TITLE
`link` attribute in ffi.rs

### ISSUE THREAD

**Issue by itpetey** [netvl/ejdb.rs#4] opened 2016-09-13 11:40 UTC
Hey mate,

I'm not able to compile this lib on OS X as I get loads of "Undefined symbols for arch..." errors. If I add a link attribute to the main `extern "C"` (line 600) in `ffi.rs` then it starts working:

``` rust
#[link(name = "ejdb")]
extern "C" {
```

Is there any harm in adding this to the library?

**Comment by netvl** [comment] 2016-09-16 11:08
No, this is explicitly against Cargo recommendations about building a binding to a native library and it is actually addressed by the `links` option in `ejdb-sys` crate. Whatever the reason, it seems to be elsewhere, likely caused by the problem with pkg-config you described in another ticket.

**Closed as completed by netvl** 2016-09-16 11:08 UTC
